# Generated by Django 5.2.5 on 2025-09-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('preco_por_unidade', models.FloatField()),
            ],
        ),
    ]
